import os

LANGUAGE = os.environ.get('SIGMA_LANGUAGE', 'en')

MESSAGES = {
    'Sigma Splitter': 'Sigma Splitter',
    'Paths are relative to the folder where you started the menu.': 'Đường dẫn tương đối được tính từ thư mục bạn mở menu.',
    'Current setup': 'Cấu hình hiện tại',
    'No sources yet. Choose 1 to add your first folder.': 'Chưa có nguồn nào. Chọn 1 để thêm thư mục đầu tiên.',
    'Source {number}: {path}': 'Nguồn {number}: {path}',
    'Output folder: {path}': 'Thư mục kết quả: {path}',
    'Extra tags: {tags}': 'Tag bổ sung: {tags}',
    'none': 'không có',
    'Rules per bundle: {size}': 'Số rule mỗi bundle: {size}',
    'Mode: {mode}': 'Chế độ: {mode}',
    'Classify only': 'Chỉ phân loại',
    'Classify and convert': 'Phân loại và chuyển đổi',
    'Sigma executable: {path}': 'Chương trình sigma: {path}',
    '1. Manage sources\n2. Output folder\n3. Extra tags\n4. Bundle size\n5. Switch conversion mode\n6. Sigma executable\n7. Preview command\n8. Run conversion\n9. Kibana address and Space\n10. Test Kibana connection\n11. Import bundles\n12. Kibana credentials\n13. Change language\n0. Exit': '1. Thêm hoặc xóa nguồn\n2. Thư mục kết quả\n3. Tag bổ sung\n4. Số rule mỗi bundle\n5. Đổi chế độ chuyển đổi\n6. Chương trình sigma\n7. Xem lệnh sẽ chạy\n8. Bắt đầu chuyển đổi\n9. Địa chỉ Kibana và Space\n10. Kiểm tra kết nối Kibana\n11. Import bundle\n12. Tài khoản hoặc API key Kibana\n13. Đổi ngôn ngữ\n0. Thoát',
    'Your choice: ': 'Bạn muốn làm gì: ',
    'Please choose one of the numbers shown above.': 'Bạn chọn một trong các số ở trên nhé.',
    'Goodbye.': 'Đã thoát menu.',
    'Sources': 'Danh sách nguồn',
    '1. Add a folder\n2. Remove a folder\n0. Back': '1. Thêm thư mục\n2. Xóa một thư mục\n0. Quay lại',
    'Folder to add (Enter to cancel): ': 'Thư mục muốn thêm (Enter để quay lại): ',
    'Added source {number}: {path}': 'Đã thêm nguồn {number}: {path}',
    'Add another folder? [y/N]: ': 'Bạn muốn thêm thư mục nữa không? [y/N]: ',
    'Source number to remove (Enter to cancel): ': 'Số thứ tự nguồn muốn xóa (Enter để quay lại): ',
    'Removed: {path}': 'Đã xóa nguồn: {path}',
    'That source number is not in the list.': 'Số thứ tự này chưa có trong danh sách.',
    'Could not add this folder: {error}': 'Chưa thêm được thư mục này: {error}',
    'Add at least one source folder first.': 'Bạn cần thêm ít nhất một thư mục nguồn trước khi chạy.',
    'Source folder does not exist: {path}': 'Không tìm thấy thư mục nguồn: {path}',
    'Choose rules, rules-emerging-threats, or a folder inside either: {path}': 'Bạn chọn rules, rules-emerging-threats hoặc thư mục con bên trong: {path}',
    'These source folders overlap: {first} and {second}': 'Hai nguồn bị trùng hoặc chồng lấn: {first} và {second}',
    'Use folders from the same collection root for {collection}.': 'Với {collection}, hãy chọn các thư mục thuộc cùng một thư mục gốc collection.',
    'Source and output folders must not overlap.': 'Thư mục nguồn và kết quả không được nằm trong nhau.',
    'Choose a new or empty output folder: {path}': 'Bạn chọn thư mục kết quả mới hoặc đang trống: {path}',
    'Splitter script is missing: {path}': 'Thiếu script chuyển đổi: {path}',
    'Output folder': 'Thư mục kết quả',
    'Enter one tag per line. A blank line finishes and replaces the previous extra tags.': 'Bạn nhập mỗi tag trên một dòng. Enter ở dòng trống để kết thúc và thay danh sách tag bổ sung cũ.',
    'Tag: ': 'Tag: ',
    'Maximum rules per bundle: ': 'Số rule tối đa mỗi bundle: ',
    'Please enter a positive integer. The previous value is unchanged.': 'Bạn nhập số nguyên lớn hơn 0 nhé. Giá trị cũ vẫn được giữ lại.',
    'Executable name or path': 'Tên hoặc đường dẫn chương trình',
    'Cannot start yet: {error}': 'Chưa thể bắt đầu: {error}',
    'Command: {command}': 'Lệnh sẽ chạy: {command}',
    'Start with this setup? [y/N]: ': 'Bắt đầu với cấu hình này nhé? [y/N]: ',
    'Cancelled. No output was created.': 'Đã hủy. Chưa tạo kết quả mới.',
    'Working on your rules. This may take a few minutes...': 'Đang xử lý rule. Bước này có thể mất vài phút...',
    'Conversion finished. Review the manifest before importing.': 'Đã xử lý xong. Bạn xem manifest trước khi import nhé.',
    'Conversion stopped with exit code {code}.': 'Quá trình xử lý gặp lỗi, mã thoát {code}.',
    'Could not start the splitter: {error}': 'Không khởi chạy được script: {error}',
    'Results': 'Kết quả xử lý',
    'Source rules: {count}': 'Tổng rule nguồn: {count}',
    'Converted rules: {count}': 'Rule đã chuyển đổi: {count}',
    'Rules in bundles: {count}': 'Rule trong bundle: {count}',
    'Bundles: {count}': 'Số bundle: {count}',
    'Rule error {source}: {error}': 'Lỗi rule {source}: {error}',
    '{count} more errors are listed in manifest.csv.': 'Còn {count} lỗi khác trong manifest.csv.',
    'Output: {path}': 'Kết quả được lưu tại: {path}',
    'Could not read the report: {error}': 'Không đọc được báo cáo: {error}',
    'Kibana URL (include https:// or http://)': 'URL Kibana (nhớ thêm https:// hoặc http://)',
    'Space ID (Enter for default): ': 'Space ID (Enter để dùng mặc định): ',
    'CA certificate path (Enter for system CA): ': 'Đường dẫn CA certificate (Enter để dùng CA hệ thống): ',
    'Kibana address updated.': 'Đã cập nhật địa chỉ Kibana.',
    'Could not use that setup: {error}': 'Chưa dùng được cấu hình này: {error}',
    'NDJSON file or bundles folder': 'File NDJSON hoặc thư mục bundle',
    'Import complete.': 'Đã import xong.',
    'Import is incomplete. Review the report above before trying again.': 'Import chưa hoàn tất. Bạn xem báo cáo ở trên trước khi thử lại nhé.',
    'API error: {error}': 'Lỗi API: {error}',
    'Username must not contain a colon.': 'Username không được chứa dấu hai chấm.',
    'Authentication: {method}': 'Cách xác thực: {method}',
    'API key is set': 'Đã có API key',
    'Username/password are set': 'Đã có username/password',
    'Not configured': 'Chưa cấu hình',
    '1. API key\n2. Username and password\n3. Clear credentials\n0. Back': '1. API key\n2. Username và password\n3. Xóa thông tin xác thực\n0. Quay lại',
    'Encoded API key (hidden; Enter to cancel): ': 'API key dạng encoded (được che; Enter để quay lại): ',
    'Username (Enter to cancel): ': 'Username (Enter để quay lại): ',
    'Password (hidden; Enter to cancel): ': 'Password (được che; Enter để quay lại): ',
    'Credentials updated for this menu session. They are not saved to disk or your parent shell.': 'Đã cập nhật thông tin xác thực cho phiên menu này. Thông tin không được lưu ra đĩa hoặc đổi shell đang mở.',
    'Credentials cleared for this menu session.': 'Đã xóa thông tin xác thực trong phiên menu này.',
    'No changes were made.': 'Chưa thay đổi cấu hình.',
    'Hidden input requires an interactive terminal. Please run the menu in your terminal.': 'Nhập thông tin bí mật cần terminal tương tác. Bạn chạy menu trực tiếp trong terminal nhé.',
    'The menu was stopped. If a request was in progress, check the output and Kibana before retrying.': 'Đã dừng menu. Nếu đang xử lý hoặc gửi request, bạn kiểm tra kết quả và Kibana trước khi thử lại nhé.',
    'Kibana URL must include http:// or https:// and must not contain credentials, a query, or a fragment.': 'URL Kibana cần có http:// hoặc https://, không kèm thông tin đăng nhập, query hoặc fragment.',
    'Use an encoded API key without control characters.': 'Bạn dùng API key dạng encoded, không chứa ký tự điều khiển nhé.',
    'Set an API key or both a username and password. In the menu, choose Kibana credentials.': 'Bạn cấu hình API key hoặc cả username/password nhé. Trong menu, chọn mục thông tin xác thực Kibana.',
    'Timeout must be greater than zero.': 'Timeout cần lớn hơn 0.',
    'Connection error: {error}': 'Lỗi kết nối: {error}',
    'The API did not return valid JSON. Check the Kibana URL and reverse proxy.': 'API chưa trả JSON hợp lệ. Bạn kiểm tra lại URL Kibana và reverse proxy nhé.',
    'The API response is not a JSON object.': 'Phản hồi API không phải JSON object.',
    'This is not a Detection Rules API response.': 'Phản hồi chưa đúng định dạng Detection Rules API.',
    'Connected to {target}; Detection Rules API is readable.': 'Đã kết nối tới {target} và đọc được Detection Rules API.',
    'Read access does not confirm import permission.': 'Quyền đọc chưa xác nhận quyền import.',
    'No NDJSON files found in: {path}': 'Chưa có file NDJSON trong: {path}',
    'Not an NDJSON file: {path}': 'Đây không phải file NDJSON: {path}',
    '{file}, line {line}: invalid JSON.': '{file}, dòng {line}: JSON chưa hợp lệ.',
    '{file}, line {line}: every rule must have enabled=false.': '{file}, dòng {line}: mỗi rule cần có enabled=false.',
    '{file}, line {line}: a nonempty rule_id is required.': '{file}, dòng {line}: rule cần có rule_id không rỗng.',
    'Duplicate rule ID in the selected files: {rule_id}': 'ID rule bị trùng trong các file đã chọn: {rule_id}',
    'File contains no rules: {path}': 'File chưa có rule nào: {path}',
    'Importing {file}: {count} rules...': 'Đang import {file}: {count} rule...',
    'Request started; no confirmed result yet.': 'Đã bắt đầu gửi request; chưa có kết quả xác nhận.',
    'Invalid response field: {field}.': 'Trường phản hồi chưa hợp lệ: {field}.',
    'The API response has no valid success_count.': 'Phản hồi API chưa có success_count hợp lệ.',
    'The API has not confirmed that all rules were imported.': 'API chưa xác nhận toàn bộ rule được import.',
    'Stopped this batch. Remaining files were not sent; no automatic retry.': 'Đã dừng batch. Các file còn lại chưa được gửi; chương trình không tự thử lại.',
    '{status}: {done}/{count} rules': '{status}: {done}/{count} rule',
    '{file}: {count} rules': '{file}: {count} rule',
    'Import report: {path}': 'Báo cáo import: {path}',
    '--file must point to an NDJSON file.': '--file cần trỏ đến một file NDJSON.',
    '--bundles must point to a bundles folder.': '--bundles cần trỏ đến một thư mục bundle.',
    'Target: {target}': 'Đích import: {target}',
    '{files} files, {rules} Disabled rules; overwrite=false.': '{files} file, {rules} rule Disabled; overwrite=false.',
    'Dry run: no connection or upload was made.': 'Chỉ xem thử: chưa kết nối hoặc gửi file tới Kibana.',
    'Import into this Kibana target? [y/N]: ': 'Import vào Kibana này nhé? [y/N]: ',
    'Import cancelled. No files were sent.': 'Đã hủy import. Chưa gửi file.',
    'Error: {error}': 'Lỗi: {error}',
    'Stopped. If a POST was started, check Kibana before retrying.': 'Đã dừng. Nếu POST đã bắt đầu, bạn kiểm tra Kibana trước khi thử lại nhé.',
}


def set_language(language):
    global LANGUAGE
    if language not in {'vi', 'en'}:
        raise ValueError('Language must be vi or en.')
    LANGUAGE = language
    os.environ['SIGMA_LANGUAGE'] = language


def tr(message, **values):
    text = MESSAGES.get(message, message) if LANGUAGE == 'vi' else message
    return text.format(**values)
